"""Tests for the causal estimators.

The central test is recovery: on a panel generated by the exact process the
estimator assumes, with a known injected effect, the estimate must land close to
the truth. A synthetic control that cannot recover a known effect on clean data
has no business being pointed at a real project.
"""

from __future__ import annotations

import numpy as np
import pytest

from groundtruth.contracts.errors import EstimationError, InsufficientDataError
from groundtruth.engine.causal.did import estimate_did
from groundtruth.engine.causal.synthetic_control import (
    _project_to_simplex,
    fit_synthetic_control,
    solve_simplex_least_squares,
)


class TestSimplexProjection:
    def test_projection_lands_on_the_simplex(self, rng):
        for _ in range(20):
            v = rng.normal(size=12) * 3.0
            w = _project_to_simplex(v)
            assert w.sum() == pytest.approx(1.0)
            assert (w >= -1e-12).all()

    def test_point_already_on_simplex_is_unchanged(self):
        v = np.array([0.2, 0.3, 0.5])
        assert _project_to_simplex(v) == pytest.approx(v)

    def test_projection_is_sparse_for_extreme_inputs(self):
        w = _project_to_simplex(np.array([10.0, -5.0, -5.0]))
        assert w == pytest.approx([1.0, 0.0, 0.0])


class TestSimplexLeastSquares:
    def test_recovers_known_convex_combination(self, rng):
        donors = rng.normal(size=(30, 4))
        true_w = np.array([0.5, 0.3, 0.2, 0.0])
        treated = donors @ true_w
        w, _, converged = solve_simplex_least_squares(donors, treated)
        assert converged
        assert w == pytest.approx(true_w, abs=1e-3)

    def test_weights_always_satisfy_the_constraints(self, rng):
        donors = rng.normal(size=(15, 8))
        treated = rng.normal(size=15)
        w, _, _ = solve_simplex_least_squares(donors, treated)
        assert w.sum() == pytest.approx(1.0)
        assert (w >= -1e-12).all()

    def test_rejects_empty_donor_pool(self):
        with pytest.raises(EstimationError):
            solve_simplex_least_squares(np.zeros((5, 0)), np.zeros(5))

    def test_ridge_spreads_weight_across_collinear_donors(self, rng):
        base = rng.normal(size=(30, 1))
        donors = np.hstack([base, base + 1e-6 * rng.normal(size=(30, 1)), rng.normal(size=(30, 2))])
        treated = base.ravel()
        sparse, _, _ = solve_simplex_least_squares(donors, treated, ridge=0.0)
        spread, _, _ = solve_simplex_least_squares(donors, treated, ridge=1.0)
        assert spread.max() <= sparse.max() + 1e-6


class TestSyntheticControl:
    def test_recovers_a_known_injected_effect(self, factor_panel):
        outcomes, unit_ids, n_pre, true_effect = factor_panel
        fit = fit_synthetic_control(outcomes[:, 0], outcomes[:, 1:], unit_ids[1:], n_pre)
        assert fit.average_effect == pytest.approx(true_effect, abs=0.015)

    def test_reports_no_effect_when_none_exists(self, null_panel):
        outcomes, unit_ids, n_pre = null_panel
        fit = fit_synthetic_control(outcomes[:, 0], outcomes[:, 1:], unit_ids[1:], n_pre)
        assert abs(fit.average_effect) < 0.02

    def test_pre_period_fit_is_tight_on_clean_data(self, factor_panel):
        outcomes, unit_ids, n_pre, _ = factor_panel
        fit = fit_synthetic_control(outcomes[:, 0], outcomes[:, 1:], unit_ids[1:], n_pre)
        assert fit.pre_rmspe < 0.02
        assert fit.converged

    def test_rmspe_ratio_is_large_when_an_effect_exists(self, factor_panel):
        outcomes, unit_ids, n_pre, _ = factor_panel
        fit = fit_synthetic_control(outcomes[:, 0], outcomes[:, 1:], unit_ids[1:], n_pre)
        assert fit.rmspe_ratio > 2.0

    def test_contributing_donors_are_sparse_and_sum_to_one(self, factor_panel):
        outcomes, unit_ids, n_pre, _ = factor_panel
        fit = fit_synthetic_control(outcomes[:, 0], outcomes[:, 1:], unit_ids[1:], n_pre)
        contributing = fit.contributing_donors()
        assert 0 < len(contributing) <= len(unit_ids) - 1
        assert sum(contributing.values()) == pytest.approx(1.0, abs=1e-3)

    def test_cumulative_effect_is_the_sum_of_gaps(self, factor_panel):
        outcomes, unit_ids, n_pre, _ = factor_panel
        fit = fit_synthetic_control(outcomes[:, 0], outcomes[:, 1:], unit_ids[1:], n_pre)
        assert fit.cumulative_effect == pytest.approx(fit.gap_post.sum())

    def test_refuses_a_short_pre_period(self, factor_panel):
        outcomes, unit_ids, _, _ = factor_panel
        with pytest.raises(InsufficientDataError, match="below the minimum"):
            fit_synthetic_control(outcomes[:, 0], outcomes[:, 1:], unit_ids[1:], 3)

    def test_refuses_when_there_is_no_post_period(self, factor_panel):
        outcomes, unit_ids, _, _ = factor_panel
        with pytest.raises(InsufficientDataError, match="no post-treatment"):
            fit_synthetic_control(outcomes[:, 0], outcomes[:, 1:], unit_ids[1:], outcomes.shape[0])

    def test_rejects_non_finite_inputs_rather_than_imputing(self, factor_panel):
        outcomes, unit_ids, n_pre, _ = factor_panel
        corrupted = outcomes.copy()
        corrupted[3, 2] = np.nan
        with pytest.raises(EstimationError, match="non-finite"):
            fit_synthetic_control(corrupted[:, 0], corrupted[:, 1:], unit_ids[1:], n_pre)

    def test_rejects_mismatched_donor_ids(self, factor_panel):
        outcomes, unit_ids, n_pre, _ = factor_panel
        with pytest.raises(EstimationError, match="donor_ids length"):
            fit_synthetic_control(outcomes[:, 0], outcomes[:, 1:], unit_ids[1:-1], n_pre)


class TestDifferenceInDifferences:
    def test_recovers_an_effect_under_parallel_trends(self):
        n_periods, n_controls, n_pre = 20, 10, 10
        base = np.linspace(0.5, 0.6, n_periods)
        controls = np.tile(base[:, None], (1, n_controls)) + np.linspace(-0.01, 0.01, n_controls)
        treated = base.copy()
        treated[n_pre:] += 0.05
        result = estimate_did(treated, controls, n_pre)
        assert result.estimate == pytest.approx(0.05, abs=1e-6)
        assert result.pre_trend_divergence == pytest.approx(0.0, abs=1e-9)
        assert result.parallel_trends_plausible

    def test_flags_its_own_unreliability_when_pre_trends_diverge(self):
        n_periods, n_controls, n_pre = 20, 10, 10
        controls = np.tile(np.full(n_periods, 0.5)[:, None], (1, n_controls))
        controls += np.linspace(-0.01, 0.01, n_controls)
        treated = 0.5 + 0.02 * np.arange(n_periods)  # strong independent uptrend
        result = estimate_did(treated, controls, n_pre)
        assert not result.parallel_trends_plausible

    def test_requires_enough_pre_periods_to_assess_trends(self):
        with pytest.raises(InsufficientDataError):
            estimate_did(np.linspace(0, 1, 10), np.zeros((10, 3)), 2)

    def test_requires_at_least_one_control(self):
        with pytest.raises(EstimationError):
            estimate_did(np.linspace(0, 1, 10), np.zeros((10, 0)), 5)

    def test_standard_error_is_none_for_a_single_control(self):
        result = estimate_did(np.linspace(0.5, 0.7, 12), np.full((12, 1), 0.5), 6)
        assert result.standard_error is None
